services:
  # Backend API Service
  - type: web
    name: myanmar-betting-api
    env: docker
    dockerfilePath: ./backend/Dockerfile
    region: singapore
    plan: free
    branch: main
    healthCheckPath: /api/health-check
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://myanmar-betting-api.onrender.com
      - key: FRONTEND_URL
        value: https://myanmar-betting.onrender.com
      - key: SESSION_DOMAIN
        value: .onrender.com
      - key: SANCTUM_STATEFUL_DOMAINS
        value: myanmar-betting.onrender.com
      - key: CORS_ALLOWED_ORIGINS
        value: https://myanmar-betting.onrender.com
      - key: DB_CONNECTION
        value: mysql
      - key: MYSQLHOST
        fromDatabase:
          name: myanmar-betting-db
          property: host
      - key: MYSQLPORT
        fromDatabase:
          name: myanmar-betting-db
          property: port
      - key: MYSQLDATABASE
        fromDatabase:
          name: myanmar-betting-db
          property: database
      - key: MYSQLUSER
        fromDatabase:
          name: myanmar-betting-db
          property: user
      - key: MYSQLPASSWORD
        fromDatabase:
          name: myanmar-betting-db
          property: password

  # Frontend Service
  - type: web
    name: myanmar-betting
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/dist
    pullRequestPreviewsEnabled: true
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_BASE_URL
        value: https://myanmar-betting-api.onrender.com

databases:
  - name: myanmar-betting-db
    region: singapore
    plan: free
