services:
  # Backend API Service
  - type: web
    name: myanmar-betting-api
    env: docker
    dockerfilePath: ./backend/Dockerfile
    buildCommand: cd backend && composer install && php artisan key:generate && php artisan migrate
    startCommand: cd backend && php artisan serve --host 0.0.0.0 --port $PORT
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromDatabase:
          name: myanmar-betting-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: myanmar-betting-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: myanmar-betting-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: myanmar-betting-db
          property: username
      - key: DB_PASSWORD
        fromDatabase:
          name: myanmar-betting-db
          property: password
      - key: SESSION_DOMAIN
        value: .onrender.com
      - key: SANCTUM_STATEFUL_DOMAINS
        value: localhost:5173,myanmar-betting.onrender.com
      - key: CORS_ALLOWED_ORIGINS
        value: http://localhost:5173,https://myanmar-betting.onrender.com
      - key: SESSION_DRIVER
        value: cookie

  # Frontend Static Site
  - type: web
    name: myanmar-betting-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/dist
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
      - path: /*
        name: X-Frame-Options
        value: DENY
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        value: https://myanmar-betting-api.onrender.com

databases:
  - name: myanmar-betting-db
    databaseName: myanmar_betting
    user: myanmar_betting
    ipAllowList: [] # only allow internal connections
